### ISSUE TITLE
Can the widget be scaled?

### ISSUE THREAD

**Issue by SpamWall** [Blokkendoos/tkCompass#1]
I'd like it to be about 2/3 the size in X and Y.  is there a way to scale the image down?  If I just edit the image files will the code self-correct?

**Comment by Blokkendoos** [comment]
Scaling the image should work. Just give it  a try.
Edit and export as png both image/compass.svg and image/compass_disc.svg

**Comment by Blokkendoos** [comment]
Scaling should work, just give it a try.
Edit and export as png both image/compass.svg and image/compass_disc.svg

**Comment by Blokkendoos** [comment]
Consider the suggested approach works
